### ISSUE TITLE
Cannot boot

### ISSUE THREAD

**Issue by GSchroder** [ramsey/macos-vagrant-box#1]
When booting, UFI startup shell script runs (boot manager set to look at HDD before running the script), searches and finds boot loader "fs5:\System\Library\CoreServices\boot.efi", says launching and then does nothing?

**Comment by ramsey** [comment]
Can you share your `Vagrantfile` and which box you're attempting to use? Thanks!

**Comment by echochio-tw** [comment]
vagrant init ramsey/macos-catalina
Cannot boot me to

**Comment by ramsey** [comment]
Please share the full terminal output so I can try to debug this. Thanks!

**Comment by elasim** [comment]
before this came out, vm was reboot several times and os boot log shown up at that time.

![03BCA918-6767-4C0B-A4E1-6ED20B1F6A36](https://user-images.githubusercontent.com/1837682/72766884-30548480-3c35-11ea-903d-7454ca7dddea.png)

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ramsey/macos-catalina'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ramsey/macos-catalina' is up to date...
==> default: Setting the name of the VM: catalina_default_1579568255286_7260
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'paused' state. Please verify everything is configured
properly and try again.
If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

**Comment by ramsey** [comment]
What is your host operating system, and what version of VirtualBox are you using?

**Comment by elasim** [comment]
virtualbox-5.2.34_Ubuntur133883
Ubuntu 18.04.3 (4.15.0-70-generic)

Sorry, I couldn't get any boot log. its disappear too quickly. and safe mode is not working also.

**Comment by echochio-tw** [comment]
win10 home 10.0.18363.592
virtualbox 6.0.16 r135674 (Qt5.6.2)
Vagrant 2.2.5

Sorry, no get log , Will try again

**Comment by ramsey** [comment]
I think the reason it won’t boot is because macOS will only run on certified Apple hardware. Running it on anything else is a violation of their license agreement.

**Comment by echochio-tw** [comment]
https://gist.github.com/StudioEtrange/31bddcb386d7f0d9920968e693a78246

mybe can work .....

**Comment by ramsey** [comment]
That’s a different Vagrant box. I can’t support running this box on anything other than Apple hardware because it’s against their license.

**Comment by aguillement** [comment]
I had the exact same issue on : 
Windows10 Pro
Virtualbox 6.0.18
Vagrant 2.2.7

Trying to build `ramsey/macos-catalina`

With the gist linked by @echochio-tw, have added this to my Vagrantfile : 
```
  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
  end
```
And it's working well.

**Comment by ridvanaltun** [comment]
> I had the exact same issue on :
> Windows10 Pro
> Virtualbox 6.0.18
> Vagrant 2.2.7
> 
> Trying to build `ramsey/macos-catalina`
> 
> With the gist linked by @echochio-tw, have added this to my Vagrantfile :
> 
> ```
>   config.vm.provider "virtualbox" do |vb|
>       vb.customize ["modifyvm", :id, "--cpuidset", "1","000206a7","02100800","1fbae3bf","bfebfbff"]
>       vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
>       vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
>       vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
>       vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
>   end
> ```
> 
> And it's working well.

This configuration works with `ramsey/macos-mojave` too.

**Comment by jpruiz114** [comment]
I'm having the exact same issue. My machine is trapped in a loop:

![VirtualBox_macos-test-catalina-v1_31_03_2020_19_39_45](https://user-images.githubusercontent.com/4614970/78084907-704b8c80-7387-11ea-931d-bf3cec27d987.png)

Any advice? Thanks.

**Comment by ramsey** [comment]
Are you running this on Apple hardware?

**Comment by jpruiz114** [comment]
I'm not. I'm running this vagrant box on a PC running Windows 10.

**Comment by jpruiz114** [comment]
@ramsey:

This is the vagrant file I used to provision your machine:

```
Vagrant.configure("2") do |config|
  config.vm.box = "ramsey/macos-catalina"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "macos-test-catalina-v1"
    vb.customize ["modifyvm", :id, "--cpus", 2]
		vb.customize ["modifyvm", :id, "--memory", 8192]
		vb.customize ["modifyvm", :id, "--vram", 256]
		vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
```

I have another macOS vagrant box which works with my PC on top of Windows 10:

```
Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "macos-test-sierra-v1"
    vb.customize ["modifyvm", :id, "--cpus", 2]
		vb.customize ["modifyvm", :id, "--memory", 8192]
		vb.customize ["modifyvm", :id, "--vram", 256]
		vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
```

Not sure if having another box to compare might help. Thanks.

**Comment by ramsey** [comment]
This box will only run on certified Apple hardware. Unfortunately, I'm not able to help if your host system is Windows or Linux.

**Comment by jpruiz114** [comment]
Thanks for getting back @ramsey. Not sure if you did tests using other OS as host but other Vagrant boxes for macOS work under Windows 10. Do you know why would that be? Thanks again.

**Comment by ramsey** [comment]
Attempting to run macOS on non-certified Apple hardware is a violation of their EULA. So, I can’t help. If you’re able to get it running through another means or with another box, go for it. Cheers!
