### ISSUE TITLE
When booting to EFI prompt on ramsey/macos-catalina /usr/bin is absent and so cannot disable csrutil

### ISSUE THREAD

**Issue by matt-darwin** [ramsey/macos-vagrant-box#6]
I've updated to the latest version of Catalina inside a macos-catalina box along with some tools like brew and ansible, however this now has some leftover junk in /Library/Updates that I want to remove in order to repackage the box.

Booting into EFI command from the boot loader works fine, however in FS2: the /usr/bin directory which would normally contain csrutil is missing, and so I cannot disable csrutil in order to clean up the junk.

I don't know a way of booting into safe mode from VirtualBox so I was under the impression that EFI command is the only way in order to do this.  csrutil is present ok on the main os partition.

**Comment by matt-darwin** [comment]
Never mind, found the boot loader for recovery mode and run from in there.

**Comment by ramsey** [comment]
Glad you were able to resolve this. Would you mind posting some more information about how you were able to boot into recovery mode, in case it helps others with similar issues in the future?

**Comment by matt-darwin** [comment]
Yes of course, here's what I did:-

_To clear any updates left in /Library/Updates you need to enter recovery mode. Start the VirtualBox VM and immediately tap ESC to get into the BIOS. Select Boot Loader -> EFI Command Line then press enter. Press ESC again to load the command line. On the command line change to the FS1: drive, and cd to the directory shown. Within will be a file boot.efi, run this and this will boot to Recovery Mode. You can then use the terminal to run csrutil disable, perform a soft restart, and then remove the files you wish from /Library/Updates. Following a hard reset csrutil will be re-enabled._
